swagger: "2.0"
info:
  version: "0.0.1"
  title: api server
# during dev, should point to your local machine
host: localhost:9960
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http

# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /api/v1/parsers:
    get:
      description: Gets `GrabStore` objects.
      # used as the method name of the controller
      operationId: get-parser
      parameters:
        - name: name
          in: query
          description: The name of the person to whom to say hello
          required: false
          type: string
      responses:
        # Response code
        200:
          description: Successful response
          # A schema describing your response object.
          # Use JSON Schema format
          schema:
            type: object
            required:
            - results
            properties:
              success:
                type: string
              results:
                type: array
                items:
                  $ref: '#/definitions/GrabStore'
  /swagger:
    x-swagger-pipe: swagger_raw

definitions:
   GrabStore:
    type: object
    properties:
      sku:
        type: string
      amount:
        type: integer
      mfs:
        type: string
      pn:
        type: string
      description:
        type: string
      lead:
        type: boolean
      rohs:
        type: boolean
      url:
        type: string
      ip:
        type: string
      uuid:
        type: string
      attributes:
        type: array
        items:
          properties:
            key:
              type: string
            value:
              type: string
      documents:
        type: array
        items:
          type: string
      priceStores:
        type: array
        items:
          properties:
            amount:
              type: integer
            unitPrice:
              type: string
  
